//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.21 at 11:58:02 PM BST 
//


package com.gomeznetworks.jaxb.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MonitorDesignator"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="MonitorClassDesignator" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TXTEST" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="PAGE"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="OBJECT" maxOccurs="unbounded"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;attribute name="oseq" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                                     &lt;attribute name="hid" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                                     &lt;attribute name="connid" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                                     &lt;attribute name="rc" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                                     &lt;attribute name="ctype" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="rtime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                                     &lt;attribute name="nbyte" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                                     &lt;attribute name="fbstart" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="fbtime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                                     &lt;attribute name="contstart" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="conttime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                                     &lt;attribute name="uhost" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="upage" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="pseq" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="rtime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="nobj" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="rc200" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="rc300" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="rc400" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="rc500" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="rcnet" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="rcint" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="nbyte" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="nhost" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="nconn" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="cmtext" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="cmstat" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="tostat" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="usstat" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="blstat" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="rtobjseq" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="dnssum" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="ndns" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="connsum" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="nconn1" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="sslsum" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="nssl" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="fbsum" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="nfb" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="contsum" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="ncont" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="ptime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="HOST" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="CONN" maxOccurs="unbounded"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;attribute name="connid" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                                     &lt;attribute name="page" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                                     &lt;attribute name="rtime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                                     &lt;attribute name="connstart" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="conntime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                                     &lt;attribute name="nbyte" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                                     &lt;attribute name="nerr" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                                     &lt;attribute name="nobj" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="hid" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="page" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="dnsstart" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="dnstime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="nbyte" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="nerr" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="nobj" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="nconn" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="ip" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="mid" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                 &lt;attribute name="sid" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                 &lt;attribute name="ttime" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="sname" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="rtime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                 &lt;attribute name="tpt" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                 &lt;attribute name="tps" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                 &lt;attribute name="tpf" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                 &lt;attribute name="tot" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                 &lt;attribute name="tos" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                 &lt;attribute name="tof" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                 &lt;attribute name="nbyte" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                 &lt;attribute name="browsertype" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "monitorDesignator",
    "txtest"
})
@XmlRootElement(name = "GpnResponseData")
public class GpnResponseData {

    @XmlElement(name = "MonitorDesignator", required = true)
    protected GpnResponseData.MonitorDesignator monitorDesignator;
    @XmlElement(name = "TXTEST", required = true)
    protected List<GpnResponseData.TXTEST> txtest;

    /**
     * Gets the value of the monitorDesignator property.
     * 
     * @return
     *     possible object is
     *     {@link GpnResponseData.MonitorDesignator }
     *     
     */
    public GpnResponseData.MonitorDesignator getMonitorDesignator() {
        return monitorDesignator;
    }

    /**
     * Sets the value of the monitorDesignator property.
     * 
     * @param value
     *     allowed object is
     *     {@link GpnResponseData.MonitorDesignator }
     *     
     */
    public void setMonitorDesignator(GpnResponseData.MonitorDesignator value) {
        this.monitorDesignator = value;
    }

    /**
     * Gets the value of the txtest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the txtest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTXTEST().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GpnResponseData.TXTEST }
     * 
     * 
     */
    public List<GpnResponseData.TXTEST> getTXTEST() {
        if (txtest == null) {
            txtest = new ArrayList<GpnResponseData.TXTEST>();
        }
        return this.txtest;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="MonitorClassDesignator" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class MonitorDesignator {

        @XmlAttribute(name = "MonitorClassDesignator")
        protected String monitorClassDesignator;

        /**
         * Gets the value of the monitorClassDesignator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMonitorClassDesignator() {
            return monitorClassDesignator;
        }

        /**
         * Sets the value of the monitorClassDesignator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMonitorClassDesignator(String value) {
            this.monitorClassDesignator = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="PAGE"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="OBJECT" maxOccurs="unbounded"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;attribute name="oseq" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                           &lt;attribute name="hid" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                           &lt;attribute name="connid" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                           &lt;attribute name="rc" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                           &lt;attribute name="ctype" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="rtime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                           &lt;attribute name="nbyte" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                           &lt;attribute name="fbstart" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="fbtime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                           &lt;attribute name="contstart" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="conttime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                           &lt;attribute name="uhost" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="upage" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="pseq" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="rtime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="nobj" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="rc200" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="rc300" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="rc400" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="rc500" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="rcnet" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="rcint" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="nbyte" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="nhost" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="nconn" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="cmtext" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="cmstat" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="tostat" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="usstat" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="blstat" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="rtobjseq" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="dnssum" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="ndns" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="connsum" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="nconn1" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="sslsum" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="nssl" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="fbsum" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="nfb" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="contsum" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="ncont" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="ptime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="HOST" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="CONN" maxOccurs="unbounded"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;attribute name="connid" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                           &lt;attribute name="page" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                           &lt;attribute name="rtime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                           &lt;attribute name="connstart" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="conntime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                           &lt;attribute name="nbyte" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                           &lt;attribute name="nerr" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                           &lt;attribute name="nobj" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="hid" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="page" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="dnsstart" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="dnstime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="nbyte" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="nerr" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="nobj" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="nconn" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="ip" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="mid" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *       &lt;attribute name="sid" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *       &lt;attribute name="ttime" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="sname" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="rtime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *       &lt;attribute name="tpt" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *       &lt;attribute name="tps" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *       &lt;attribute name="tpf" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *       &lt;attribute name="tot" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *       &lt;attribute name="tos" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *       &lt;attribute name="tof" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *       &lt;attribute name="nbyte" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *       &lt;attribute name="browsertype" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "page",
        "host"
    })
    public static class TXTEST {

        @XmlElement(name = "PAGE", required = true)
        protected GpnResponseData.TXTEST.PAGE page;
        @XmlElement(name = "HOST", required = true)
        protected List<GpnResponseData.TXTEST.HOST> host;
        @XmlAttribute(name = "mid")
        protected Integer mid;
        @XmlAttribute(name = "sid")
        protected Integer sid;
        @XmlAttribute(name = "ttime")
        protected String ttime;
        @XmlAttribute(name = "sname")
        protected String sname;
        @XmlAttribute(name = "rtime")
        protected Integer rtime;
        @XmlAttribute(name = "tpt")
        protected Integer tpt;
        @XmlAttribute(name = "tps")
        protected Integer tps;
        @XmlAttribute(name = "tpf")
        protected Integer tpf;
        @XmlAttribute(name = "tot")
        protected Integer tot;
        @XmlAttribute(name = "tos")
        protected Integer tos;
        @XmlAttribute(name = "tof")
        protected Integer tof;
        @XmlAttribute(name = "nbyte")
        protected Integer nbyte;
        @XmlAttribute(name = "browsertype")
        protected String browsertype;

        /**
         * Gets the value of the page property.
         * 
         * @return
         *     possible object is
         *     {@link GpnResponseData.TXTEST.PAGE }
         *     
         */
        public GpnResponseData.TXTEST.PAGE getPAGE() {
            return page;
        }

        /**
         * Sets the value of the page property.
         * 
         * @param value
         *     allowed object is
         *     {@link GpnResponseData.TXTEST.PAGE }
         *     
         */
        public void setPAGE(GpnResponseData.TXTEST.PAGE value) {
            this.page = value;
        }

        /**
         * Gets the value of the host property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the host property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHOST().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GpnResponseData.TXTEST.HOST }
         * 
         * 
         */
        public List<GpnResponseData.TXTEST.HOST> getHOST() {
            if (host == null) {
                host = new ArrayList<GpnResponseData.TXTEST.HOST>();
            }
            return this.host;
        }

        /**
         * Gets the value of the mid property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getMid() {
            return mid;
        }

        /**
         * Sets the value of the mid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setMid(Integer value) {
            this.mid = value;
        }

        /**
         * Gets the value of the sid property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSid() {
            return sid;
        }

        /**
         * Sets the value of the sid property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSid(Integer value) {
            this.sid = value;
        }

        /**
         * Gets the value of the ttime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTtime() {
            return ttime;
        }

        /**
         * Sets the value of the ttime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTtime(String value) {
            this.ttime = value;
        }

        /**
         * Gets the value of the sname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSname() {
            return sname;
        }

        /**
         * Sets the value of the sname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSname(String value) {
            this.sname = value;
        }

        /**
         * Gets the value of the rtime property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getRtime() {
            return rtime;
        }

        /**
         * Sets the value of the rtime property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setRtime(Integer value) {
            this.rtime = value;
        }

        /**
         * Gets the value of the tpt property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getTpt() {
            return tpt;
        }

        /**
         * Sets the value of the tpt property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setTpt(Integer value) {
            this.tpt = value;
        }

        /**
         * Gets the value of the tps property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getTps() {
            return tps;
        }

        /**
         * Sets the value of the tps property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setTps(Integer value) {
            this.tps = value;
        }

        /**
         * Gets the value of the tpf property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getTpf() {
            return tpf;
        }

        /**
         * Sets the value of the tpf property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setTpf(Integer value) {
            this.tpf = value;
        }

        /**
         * Gets the value of the tot property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getTot() {
            return tot;
        }

        /**
         * Sets the value of the tot property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setTot(Integer value) {
            this.tot = value;
        }

        /**
         * Gets the value of the tos property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getTos() {
            return tos;
        }

        /**
         * Sets the value of the tos property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setTos(Integer value) {
            this.tos = value;
        }

        /**
         * Gets the value of the tof property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getTof() {
            return tof;
        }

        /**
         * Sets the value of the tof property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setTof(Integer value) {
            this.tof = value;
        }

        /**
         * Gets the value of the nbyte property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getNbyte() {
            return nbyte;
        }

        /**
         * Sets the value of the nbyte property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setNbyte(Integer value) {
            this.nbyte = value;
        }

        /**
         * Gets the value of the browsertype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBrowsertype() {
            return browsertype;
        }

        /**
         * Sets the value of the browsertype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBrowsertype(String value) {
            this.browsertype = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="CONN" maxOccurs="unbounded"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;attribute name="connid" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *                 &lt;attribute name="page" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *                 &lt;attribute name="rtime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *                 &lt;attribute name="connstart" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="conntime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *                 &lt;attribute name="nbyte" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *                 &lt;attribute name="nerr" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *                 &lt;attribute name="nobj" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="hid" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="page" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="dnsstart" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="dnstime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="nbyte" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="nerr" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="nobj" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="nconn" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="ip" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "conn"
        })
        public static class HOST {

            @XmlElement(name = "CONN", required = true)
            protected List<GpnResponseData.TXTEST.HOST.CONN> conn;
            @XmlAttribute(name = "hid")
            protected Integer hid;
            @XmlAttribute(name = "page")
            protected Integer page;
            @XmlAttribute(name = "dnsstart")
            protected String dnsstart;
            @XmlAttribute(name = "dnstime")
            protected Integer dnstime;
            @XmlAttribute(name = "nbyte")
            protected Integer nbyte;
            @XmlAttribute(name = "nerr")
            protected Integer nerr;
            @XmlAttribute(name = "nobj")
            protected Integer nobj;
            @XmlAttribute(name = "nconn")
            protected Integer nconn;
            @XmlAttribute(name = "ip")
            protected String ip;

            /**
             * Gets the value of the conn property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the conn property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCONN().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link GpnResponseData.TXTEST.HOST.CONN }
             * 
             * 
             */
            public List<GpnResponseData.TXTEST.HOST.CONN> getCONN() {
                if (conn == null) {
                    conn = new ArrayList<GpnResponseData.TXTEST.HOST.CONN>();
                }
                return this.conn;
            }

            /**
             * Gets the value of the hid property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getHid() {
                return hid;
            }

            /**
             * Sets the value of the hid property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setHid(Integer value) {
                this.hid = value;
            }

            /**
             * Gets the value of the page property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getPage() {
                return page;
            }

            /**
             * Sets the value of the page property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setPage(Integer value) {
                this.page = value;
            }

            /**
             * Gets the value of the dnsstart property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDnsstart() {
                return dnsstart;
            }

            /**
             * Sets the value of the dnsstart property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDnsstart(String value) {
                this.dnsstart = value;
            }

            /**
             * Gets the value of the dnstime property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getDnstime() {
                return dnstime;
            }

            /**
             * Sets the value of the dnstime property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setDnstime(Integer value) {
                this.dnstime = value;
            }

            /**
             * Gets the value of the nbyte property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getNbyte() {
                return nbyte;
            }

            /**
             * Sets the value of the nbyte property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setNbyte(Integer value) {
                this.nbyte = value;
            }

            /**
             * Gets the value of the nerr property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getNerr() {
                return nerr;
            }

            /**
             * Sets the value of the nerr property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setNerr(Integer value) {
                this.nerr = value;
            }

            /**
             * Gets the value of the nobj property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getNobj() {
                return nobj;
            }

            /**
             * Sets the value of the nobj property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setNobj(Integer value) {
                this.nobj = value;
            }

            /**
             * Gets the value of the nconn property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getNconn() {
                return nconn;
            }

            /**
             * Sets the value of the nconn property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setNconn(Integer value) {
                this.nconn = value;
            }

            /**
             * Gets the value of the ip property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIp() {
                return ip;
            }

            /**
             * Sets the value of the ip property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIp(String value) {
                this.ip = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;attribute name="connid" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
             *       &lt;attribute name="page" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
             *       &lt;attribute name="rtime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
             *       &lt;attribute name="connstart" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="conntime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
             *       &lt;attribute name="nbyte" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
             *       &lt;attribute name="nerr" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
             *       &lt;attribute name="nobj" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class CONN {

                @XmlAttribute(name = "connid")
                protected Integer connid;
                @XmlAttribute(name = "page")
                protected Integer page;
                @XmlAttribute(name = "rtime")
                protected Integer rtime;
                @XmlAttribute(name = "connstart")
                protected String connstart;
                @XmlAttribute(name = "conntime")
                protected Integer conntime;
                @XmlAttribute(name = "nbyte")
                protected Integer nbyte;
                @XmlAttribute(name = "nerr")
                protected Integer nerr;
                @XmlAttribute(name = "nobj")
                protected Integer nobj;

                /**
                 * Gets the value of the connid property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getConnid() {
                    return connid;
                }

                /**
                 * Sets the value of the connid property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setConnid(Integer value) {
                    this.connid = value;
                }

                /**
                 * Gets the value of the page property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getPage() {
                    return page;
                }

                /**
                 * Sets the value of the page property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setPage(Integer value) {
                    this.page = value;
                }

                /**
                 * Gets the value of the rtime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getRtime() {
                    return rtime;
                }

                /**
                 * Sets the value of the rtime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setRtime(Integer value) {
                    this.rtime = value;
                }

                /**
                 * Gets the value of the connstart property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getConnstart() {
                    return connstart;
                }

                /**
                 * Sets the value of the connstart property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setConnstart(String value) {
                    this.connstart = value;
                }

                /**
                 * Gets the value of the conntime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getConntime() {
                    return conntime;
                }

                /**
                 * Sets the value of the conntime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setConntime(Integer value) {
                    this.conntime = value;
                }

                /**
                 * Gets the value of the nbyte property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getNbyte() {
                    return nbyte;
                }

                /**
                 * Sets the value of the nbyte property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setNbyte(Integer value) {
                    this.nbyte = value;
                }

                /**
                 * Gets the value of the nerr property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getNerr() {
                    return nerr;
                }

                /**
                 * Sets the value of the nerr property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setNerr(Integer value) {
                    this.nerr = value;
                }

                /**
                 * Gets the value of the nobj property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getNobj() {
                    return nobj;
                }

                /**
                 * Sets the value of the nobj property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setNobj(Integer value) {
                    this.nobj = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="OBJECT" maxOccurs="unbounded"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;attribute name="oseq" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *                 &lt;attribute name="hid" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *                 &lt;attribute name="connid" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *                 &lt;attribute name="rc" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *                 &lt;attribute name="ctype" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="rtime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *                 &lt;attribute name="nbyte" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *                 &lt;attribute name="fbstart" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="fbtime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *                 &lt;attribute name="contstart" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="conttime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *                 &lt;attribute name="uhost" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="upage" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="pseq" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="rtime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="nobj" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="rc200" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="rc300" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="rc400" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="rc500" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="rcnet" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="rcint" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="nbyte" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="nhost" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="nconn" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="cmtext" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="cmstat" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="tostat" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="usstat" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="blstat" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="rtobjseq" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="dnssum" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="ndns" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="connsum" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="nconn1" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="sslsum" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="nssl" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="fbsum" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="nfb" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="contsum" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="ncont" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="ptime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "object"
        })
        public static class PAGE {

            @XmlElement(name = "OBJECT", required = true)
            protected List<GpnResponseData.TXTEST.PAGE.OBJECT> object;
            @XmlAttribute(name = "pseq")
            protected Integer pseq;
            @XmlAttribute(name = "rtime")
            protected Integer rtime;
            @XmlAttribute(name = "nobj")
            protected Integer nobj;
            @XmlAttribute(name = "rc200")
            protected Integer rc200;
            @XmlAttribute(name = "rc300")
            protected Integer rc300;
            @XmlAttribute(name = "rc400")
            protected Integer rc400;
            @XmlAttribute(name = "rc500")
            protected Integer rc500;
            @XmlAttribute(name = "rcnet")
            protected Integer rcnet;
            @XmlAttribute(name = "rcint")
            protected Integer rcint;
            @XmlAttribute(name = "nbyte")
            protected Integer nbyte;
            @XmlAttribute(name = "nhost")
            protected Integer nhost;
            @XmlAttribute(name = "nconn")
            protected Integer nconn;
            @XmlAttribute(name = "cmtext")
            protected String cmtext;
            @XmlAttribute(name = "cmstat")
            protected Integer cmstat;
            @XmlAttribute(name = "tostat")
            protected Integer tostat;
            @XmlAttribute(name = "usstat")
            protected Integer usstat;
            @XmlAttribute(name = "blstat")
            protected Integer blstat;
            @XmlAttribute(name = "rtobjseq")
            protected Integer rtobjseq;
            @XmlAttribute(name = "dnssum")
            protected Integer dnssum;
            @XmlAttribute(name = "ndns")
            protected Integer ndns;
            @XmlAttribute(name = "connsum")
            protected Integer connsum;
            @XmlAttribute(name = "nconn1")
            protected Integer nconn1;
            @XmlAttribute(name = "sslsum")
            protected Integer sslsum;
            @XmlAttribute(name = "nssl")
            protected Integer nssl;
            @XmlAttribute(name = "fbsum")
            protected Integer fbsum;
            @XmlAttribute(name = "nfb")
            protected Integer nfb;
            @XmlAttribute(name = "contsum")
            protected Integer contsum;
            @XmlAttribute(name = "ncont")
            protected Integer ncont;
            @XmlAttribute(name = "ptime")
            protected Integer ptime;

            /**
             * Gets the value of the object property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the object property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getOBJECT().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link GpnResponseData.TXTEST.PAGE.OBJECT }
             * 
             * 
             */
            public List<GpnResponseData.TXTEST.PAGE.OBJECT> getOBJECT() {
                if (object == null) {
                    object = new ArrayList<GpnResponseData.TXTEST.PAGE.OBJECT>();
                }
                return this.object;
            }

            /**
             * Gets the value of the pseq property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getPseq() {
                return pseq;
            }

            /**
             * Sets the value of the pseq property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setPseq(Integer value) {
                this.pseq = value;
            }

            /**
             * Gets the value of the rtime property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getRtime() {
                return rtime;
            }

            /**
             * Sets the value of the rtime property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setRtime(Integer value) {
                this.rtime = value;
            }

            /**
             * Gets the value of the nobj property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getNobj() {
                return nobj;
            }

            /**
             * Sets the value of the nobj property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setNobj(Integer value) {
                this.nobj = value;
            }

            /**
             * Gets the value of the rc200 property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getRc200() {
                return rc200;
            }

            /**
             * Sets the value of the rc200 property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setRc200(Integer value) {
                this.rc200 = value;
            }

            /**
             * Gets the value of the rc300 property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getRc300() {
                return rc300;
            }

            /**
             * Sets the value of the rc300 property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setRc300(Integer value) {
                this.rc300 = value;
            }

            /**
             * Gets the value of the rc400 property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getRc400() {
                return rc400;
            }

            /**
             * Sets the value of the rc400 property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setRc400(Integer value) {
                this.rc400 = value;
            }

            /**
             * Gets the value of the rc500 property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getRc500() {
                return rc500;
            }

            /**
             * Sets the value of the rc500 property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setRc500(Integer value) {
                this.rc500 = value;
            }

            /**
             * Gets the value of the rcnet property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getRcnet() {
                return rcnet;
            }

            /**
             * Sets the value of the rcnet property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setRcnet(Integer value) {
                this.rcnet = value;
            }

            /**
             * Gets the value of the rcint property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getRcint() {
                return rcint;
            }

            /**
             * Sets the value of the rcint property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setRcint(Integer value) {
                this.rcint = value;
            }

            /**
             * Gets the value of the nbyte property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getNbyte() {
                return nbyte;
            }

            /**
             * Sets the value of the nbyte property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setNbyte(Integer value) {
                this.nbyte = value;
            }

            /**
             * Gets the value of the nhost property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getNhost() {
                return nhost;
            }

            /**
             * Sets the value of the nhost property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setNhost(Integer value) {
                this.nhost = value;
            }

            /**
             * Gets the value of the nconn property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getNconn() {
                return nconn;
            }

            /**
             * Sets the value of the nconn property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setNconn(Integer value) {
                this.nconn = value;
            }

            /**
             * Gets the value of the cmtext property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCmtext() {
                return cmtext;
            }

            /**
             * Sets the value of the cmtext property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCmtext(String value) {
                this.cmtext = value;
            }

            /**
             * Gets the value of the cmstat property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getCmstat() {
                return cmstat;
            }

            /**
             * Sets the value of the cmstat property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setCmstat(Integer value) {
                this.cmstat = value;
            }

            /**
             * Gets the value of the tostat property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getTostat() {
                return tostat;
            }

            /**
             * Sets the value of the tostat property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setTostat(Integer value) {
                this.tostat = value;
            }

            /**
             * Gets the value of the usstat property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getUsstat() {
                return usstat;
            }

            /**
             * Sets the value of the usstat property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setUsstat(Integer value) {
                this.usstat = value;
            }

            /**
             * Gets the value of the blstat property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getBlstat() {
                return blstat;
            }

            /**
             * Sets the value of the blstat property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setBlstat(Integer value) {
                this.blstat = value;
            }

            /**
             * Gets the value of the rtobjseq property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getRtobjseq() {
                return rtobjseq;
            }

            /**
             * Sets the value of the rtobjseq property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setRtobjseq(Integer value) {
                this.rtobjseq = value;
            }

            /**
             * Gets the value of the dnssum property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getDnssum() {
                return dnssum;
            }

            /**
             * Sets the value of the dnssum property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setDnssum(Integer value) {
                this.dnssum = value;
            }

            /**
             * Gets the value of the ndns property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getNdns() {
                return ndns;
            }

            /**
             * Sets the value of the ndns property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setNdns(Integer value) {
                this.ndns = value;
            }

            /**
             * Gets the value of the connsum property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getConnsum() {
                return connsum;
            }

            /**
             * Sets the value of the connsum property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setConnsum(Integer value) {
                this.connsum = value;
            }

            /**
             * Gets the value of the nconn1 property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getNconn1() {
                return nconn1;
            }

            /**
             * Sets the value of the nconn1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setNconn1(Integer value) {
                this.nconn1 = value;
            }

            /**
             * Gets the value of the sslsum property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getSslsum() {
                return sslsum;
            }

            /**
             * Sets the value of the sslsum property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setSslsum(Integer value) {
                this.sslsum = value;
            }

            /**
             * Gets the value of the nssl property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getNssl() {
                return nssl;
            }

            /**
             * Sets the value of the nssl property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setNssl(Integer value) {
                this.nssl = value;
            }

            /**
             * Gets the value of the fbsum property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getFbsum() {
                return fbsum;
            }

            /**
             * Sets the value of the fbsum property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setFbsum(Integer value) {
                this.fbsum = value;
            }

            /**
             * Gets the value of the nfb property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getNfb() {
                return nfb;
            }

            /**
             * Sets the value of the nfb property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setNfb(Integer value) {
                this.nfb = value;
            }

            /**
             * Gets the value of the contsum property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getContsum() {
                return contsum;
            }

            /**
             * Sets the value of the contsum property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setContsum(Integer value) {
                this.contsum = value;
            }

            /**
             * Gets the value of the ncont property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getNcont() {
                return ncont;
            }

            /**
             * Sets the value of the ncont property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setNcont(Integer value) {
                this.ncont = value;
            }

            /**
             * Gets the value of the ptime property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getPtime() {
                return ptime;
            }

            /**
             * Sets the value of the ptime property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setPtime(Integer value) {
                this.ptime = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;attribute name="oseq" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
             *       &lt;attribute name="hid" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
             *       &lt;attribute name="connid" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
             *       &lt;attribute name="rc" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
             *       &lt;attribute name="ctype" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="rtime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
             *       &lt;attribute name="nbyte" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
             *       &lt;attribute name="fbstart" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="fbtime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
             *       &lt;attribute name="contstart" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="conttime" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
             *       &lt;attribute name="uhost" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="upage" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class OBJECT {

                @XmlAttribute(name = "oseq")
                protected Integer oseq;
                @XmlAttribute(name = "hid")
                protected Integer hid;
                @XmlAttribute(name = "connid")
                protected Integer connid;
                @XmlAttribute(name = "rc")
                protected Integer rc;
                @XmlAttribute(name = "ctype")
                protected String ctype;
                @XmlAttribute(name = "rtime")
                protected Integer rtime;
                @XmlAttribute(name = "nbyte")
                protected Integer nbyte;
                @XmlAttribute(name = "fbstart")
                protected String fbstart;
                @XmlAttribute(name = "fbtime")
                protected Integer fbtime;
                @XmlAttribute(name = "contstart")
                protected String contstart;
                @XmlAttribute(name = "conttime")
                protected Integer conttime;
                @XmlAttribute(name = "uhost")
                protected String uhost;
                @XmlAttribute(name = "upage")
                protected String upage;

                /**
                 * Gets the value of the oseq property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getOseq() {
                    return oseq;
                }

                /**
                 * Sets the value of the oseq property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setOseq(Integer value) {
                    this.oseq = value;
                }

                /**
                 * Gets the value of the hid property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getHid() {
                    return hid;
                }

                /**
                 * Sets the value of the hid property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setHid(Integer value) {
                    this.hid = value;
                }

                /**
                 * Gets the value of the connid property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getConnid() {
                    return connid;
                }

                /**
                 * Sets the value of the connid property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setConnid(Integer value) {
                    this.connid = value;
                }

                /**
                 * Gets the value of the rc property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getRc() {
                    return rc;
                }

                /**
                 * Sets the value of the rc property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setRc(Integer value) {
                    this.rc = value;
                }

                /**
                 * Gets the value of the ctype property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCtype() {
                    return ctype;
                }

                /**
                 * Sets the value of the ctype property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCtype(String value) {
                    this.ctype = value;
                }

                /**
                 * Gets the value of the rtime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getRtime() {
                    return rtime;
                }

                /**
                 * Sets the value of the rtime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setRtime(Integer value) {
                    this.rtime = value;
                }

                /**
                 * Gets the value of the nbyte property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getNbyte() {
                    return nbyte;
                }

                /**
                 * Sets the value of the nbyte property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setNbyte(Integer value) {
                    this.nbyte = value;
                }

                /**
                 * Gets the value of the fbstart property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFbstart() {
                    return fbstart;
                }

                /**
                 * Sets the value of the fbstart property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFbstart(String value) {
                    this.fbstart = value;
                }

                /**
                 * Gets the value of the fbtime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getFbtime() {
                    return fbtime;
                }

                /**
                 * Sets the value of the fbtime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setFbtime(Integer value) {
                    this.fbtime = value;
                }

                /**
                 * Gets the value of the contstart property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getContstart() {
                    return contstart;
                }

                /**
                 * Sets the value of the contstart property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setContstart(String value) {
                    this.contstart = value;
                }

                /**
                 * Gets the value of the conttime property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Integer }
                 *     
                 */
                public Integer getConttime() {
                    return conttime;
                }

                /**
                 * Sets the value of the conttime property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Integer }
                 *     
                 */
                public void setConttime(Integer value) {
                    this.conttime = value;
                }

                /**
                 * Gets the value of the uhost property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUhost() {
                    return uhost;
                }

                /**
                 * Sets the value of the uhost property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUhost(String value) {
                    this.uhost = value;
                }

                /**
                 * Gets the value of the upage property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUpage() {
                    return upage;
                }

                /**
                 * Sets the value of the upage property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUpage(String value) {
                    this.upage = value;
                }

            }

        }

    }

}
