//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.21 at 11:58:02 PM BST 
//


package com.gomeznetworks.jaxb.data;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GpnResponseData }
     * 
     */
    public GpnResponseData createGpnResponseData() {
        return new GpnResponseData();
    }

    /**
     * Create an instance of {@link GpnResponseData.TXTEST }
     * 
     */
    public GpnResponseData.TXTEST createGpnResponseDataTXTEST() {
        return new GpnResponseData.TXTEST();
    }

    /**
     * Create an instance of {@link GpnResponseData.TXTEST.HOST }
     * 
     */
    public GpnResponseData.TXTEST.HOST createGpnResponseDataTXTESTHOST() {
        return new GpnResponseData.TXTEST.HOST();
    }

    /**
     * Create an instance of {@link GpnResponseData.TXTEST.PAGE }
     * 
     */
    public GpnResponseData.TXTEST.PAGE createGpnResponseDataTXTESTPAGE() {
        return new GpnResponseData.TXTEST.PAGE();
    }

    /**
     * Create an instance of {@link GpnResponseData.MonitorDesignator }
     * 
     */
    public GpnResponseData.MonitorDesignator createGpnResponseDataMonitorDesignator() {
        return new GpnResponseData.MonitorDesignator();
    }

    /**
     * Create an instance of {@link GpnResponseData.TXTEST.HOST.CONN }
     * 
     */
    public GpnResponseData.TXTEST.HOST.CONN createGpnResponseDataTXTESTHOSTCONN() {
        return new GpnResponseData.TXTEST.HOST.CONN();
    }

    /**
     * Create an instance of {@link GpnResponseData.TXTEST.PAGE.OBJECT }
     * 
     */
    public GpnResponseData.TXTEST.PAGE.OBJECT createGpnResponseDataTXTESTPAGEOBJECT() {
        return new GpnResponseData.TXTEST.PAGE.OBJECT();
    }

}
